apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vioas6yzg-go 
  janus-idp.io/tekton: vioas6yzg-go
  backstage.io/kubernetes-id: vioas6yzg-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vioas6yzg-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml